# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0010_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='Favorite',
        ),
        migrations.AddField(
            model_name='album',
            name='Featured',
            field=models.BooleanField(default=False),
        ),
    ]
